# Basic Details
name = "tic-tac-toe"
version = "2.1.1"
url = "https://tictactoe.com"

[titles]
en = "Tic Tac Toe"

[descriptions]
en = "Also called naughts and crosses"

[vendor]
name = "Raven Fire Examples"
url = "https://rf.com/"

#### The Normal Scenario ####
[[scenarios]]
name = "3x3"

[scenarios.titles]
en = "Three by Three"

[scenarios.descriptions]
en = "Just the regular game"

### The X Player
[[scenarios.players]]
name = "X"
count = 1

[scenarios.players.titles]
en = "Xes"

[scenarios.players.descriptions]
en = "The X player"

[[scenarios.players.io]]
name = "actions"
spec = "http://rf.tech/specs/cards.toml"
version = ">=1.2.3"
count = "9+"

### The O Player
[[scenarios.players]]
name = "O"
count = 1

[scenarios.players.titles]
en = "Os"

[scenarios.players.descriptions]
en = "The O player"

[[scenarios.players.io]]
name = "actions"
spec = "http://rf.tech/specs/cards.toml"
version = ">=1.2.3"
count = "9+"

### The community
[[scenarios.players]]
name = "Community"
count = "1"

[scenarios.players.titles]
en = "The Community"

[scenarios.players.descriptions]
en = "Community Player"

[[scenarios.players.io]]
name = "board"
spec = "http://rf.tech/specs/screen.toml"
version = ">=1.2.3"
count = 1

