# This is the single, concatonated game file
# With all the playables, scenarios, etc
name = "spellbinder"
version = "1.7.8"
url = "https://mygameurl.com"

# Do I need a default title here? Or a default description?

# game.toml
[titles]
en = "Spellbinder: A Game of Spells and Binding"
es = "Spellbinder: un juego de hechizos y enlaces"

[descriptions]
en = "A DnD-like game with spell cards and action combat."
es = "Un juego tipo DnD con cartas de hechizos y combate de acción."

[vendor]
name = "Spellbinder Studios" # todo: name is used as a key everywhere else
url = "https://me.com/"

# scenario.campaign.toml
[[scenarios]]
name = "campaign"

[scenarios.titles]
en = "Campaign"
es = "Campaña"

[scenarios.descriptions]
en = "A campaign with a Game Master who sets the story"
es = "Una campaña con un Game Master que marca la historia"

[[scenarios.players]]
name = "GameMaster"
count = "1"

[scenarios.players.titles]
en = "english"
es = "espana"

[scenarios.players.descriptions]
en = "desc"
es = "es desc"

[[scenarios.players.io]]
name = "power_ups"
spec = "http://rf.tech/specs/cards.toml"
version = ">=1.2.3"
count = "5" # todo: This should be allowed to be a string
features = { nfc = "required", indicators = "optional" }

[[scenarios.players.io]]
name = "world_builder"
spec = "http://spellbinder-studios/spec/world_builder.toml"
version = ">=1.2.3"
count = "1"

[[scenarios.players.playables]]
name = "enemy_tokens"
spec = "http://rf.tech/specs/playables/token.toml"
version = ">0.3"
count = "20"
definition = "playables.enemies.toml"
#features = { storage = "1024" } # todo: support this in the spec

[[scenarios.players]]
name = "Adventurer"
count = "1+"

[scenarios.players.titles]
en = "english"
es = "espana"

[scenarios.players.descriptions]
en = "desc"
es = "es desc"

[[scenarios.players.io]]
name = "inventory"
spec = "http://rf.tech/specs/cards"
version = ">=1.2.3"
count = "3"
features = { nfc = "required", indicator_lights = "optional" }

[[scenarios.players.io]]
name = "action_pad"
spec = "https://rf.tech/specs/toggle_botton.toml"
version = ">=2"
count = "4"
optional = true

[[scenarios.players.playables]]
name = "champion"
spec = "https://tokens"
version = ">0.3"
count = "1"
#features = { storage = "1024" }
definition = "playables.champion.toml"

[[scenarios.players.playables]]
name = "inventory_deck"
spec = "https://rf.standard_spell_deck"
version = "=1.2"
count = "1"
definition = "playables.inventory.toml"

# The Community
[[scenarios.players]]
name = "Community"
count = "1" # this should be defaulted

# todo: a default for this, too
[scenarios.players.titles]
en = "english"
es = "espana"

[scenarios.players.descriptions]
en = "desc"
es = "es desc"

[[scenarios.players.io]]
name = "dice_roller"
spec = "https://rf.tech/specs/dice_pad.toml"
version = ">=1.2"
count = "1"

[[scenarios.campaign.players.playables]]
name = "d20"
spec = "https://dice.d20"
version = ">0.3"
count = "1"
definition = "standard"

[[scenarios.campaign.players.playables]]
name = "d6"
spec = "https://dice.d6"
version = "=1.2"
count = "1"
defined = "standard"

