[package]
name = "manifests"
version = "0.3.1"
edition = "2021"

[dependencies]
getset = "0.1.2"
common = { git = "ssh://git@github.com/ravenfire/common.git" }
serde = { version = "1.0.194", features = ["derive"] }

