name = "rf.dice_pad"
version = "1.2.1"
uuid = "18ijad8u12kfa8da8a"

[titles]
en = "Raven Fire Dice Pad"

[descriptions]
en = "The dice roller pad that comes with Sazi"

[vendor]
name = "rf.console"
url = "http://rf.console"

# This can read 4 tokens at a time
# A "die" is just a multi-sided token. It reads the one thats "down"
[features]
token_count = "4"

[[provides]]
name = "dice_pad" # The peripheral can name it whatever they like
spec = "https://rf.tech/specs/dice_pad.toml"
version = "1.2.1"


