name = "xl-card-reader"
version = "1.7.1"
uuid = "d7uajfed82ui1"

[titles]
en = "XL Card Reader"

[descriptions]
en = "A card reader deck with 10 slots"

[vendor]
name = "watertribe"
url = "http://wt.com"

[[provides]]
name = "slots" # peripheral name for the group
spec = "http://rf.tech/specs/cards.toml" # expands to rf.tech/cards
version = "1.4.2" # The version of the spec it implements
features = []
count = 10
