name = "venus-card-reader"
version = "1.2.1"

[titles]
en = "Venus Card Reader"

[descriptions]
en = "A card reader deck with 5 slots, indicator lights, and a button pad."

[vendor]
name = "venus"
url = "http://venus.com"

[[provides]]
name = "slots" # peripheral name for the group
spec = "http://rf.tech/specs/cards.toml" # expands to rf.tech/cards
version = "1.4.2" # The version of the spec it implements
features = ['rfid', 'nfc', 'barcode', 'indicators']
count = 5
# properties is unrolled

[[provides]]
name = "button_pad"
spec = "http://toggle_button.spec"
version = "2.1.5"
features = ['light']
count = 4

