name = "rf-screen"
version = "1.7.1"
uuid = "1298yujhfsa8i1"

[titles]
en = "XL Card Reader"

[descriptions]
en = "A card reader deck with 10 slots"

[vendor]
name = "watertribe"
url = "http://wt.com"

[[provides]]
name = "display" # peripheral name for the group
spec = "http://rf.tech/specs/screen.toml" # expands to rf.tech/cards
version = "2.1.2" # The version of the spec it implements
features = []
count = 1

