name = "game.gm_world_builder"
version = "1.1.7"

[vendor]
name = "world_builder"
url = "https://sb.com/world_builder"

[titles]
en = "Spellbinder Game Master World Builder"

[descriptions] 
en = "The World Building Suite on a Laptop"

[[provides]]
name = "worldbuilder"
spec = "http://spellbinder-studios/spec/world_builder.toml"
version = "2.1.0"
# count defaults to 1
